name: bs_flutter
description: "Flutter client for Bill Splitter"

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.3
  image_picker: ^1.2.1
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  dynamic_color: ^1.8.1
  url_launcher: ^6.3.2
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  hive_ce: ^2.7.0
  path_provider: ^2.1.4
  shimmer: ^3.0.0
  go_router: ^14.1.3
  dotted_border: ^3.1.0
  dotted_line: ^3.2.3
  path: ^1.9.1
  connectivity_plus: ^6.0.0
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent.git
      ref: master
  share_plus: ^12.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  freezed: ^3.2.4
  hive_ce_generator: ^1.11.0
  json_serializable: ^6.11.3
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: jetbrains_mono
      fonts:
        - asset: assets/fonts/JetBrainsMono-VariableFont_wght.ttf
          weight: 400
